- name: enable nginx:1.24
  ansible.builtin.command: dnf module enable nginx:1.24 -y

- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: remove the entire directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: start and enable nginx server
  ansible.builtin.service:
    state: restarted
    enabled: yes
    name: nginx

- name: download frontend
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/{{component}}-v3.zip
    dest: /tmp/frontend.zip

- name: unarchieve frontend
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: remove default nginx
  ansible.builtin.file:
    state: absent
    path: /etc/nginx/nginx.conf

- name: copy the nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart the nginx
