- name: copy rabbitmq repo
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: install rabbitmq server
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: present

- name: start and enable the service
  ansible.builtin.service:
    state: restarted
    enabled: yes
    name: rabbitmq-server

- name: create rabbitmq user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    permissions:
    - vhost: /
      configure_priv: .*
      read_priv: .*
      write_priv: .*
    state: present
  # telnet  redis-dev.sanathananelaform.online 6379
  # restart the services
  # ssh  ec2-user@cart-dev.sanathananelaform.online 'sudo systemctl restart cart'
