- name: app setup
  ansible.builtin.import_role:
    name: common
    taks_from: app-setup.yaml

- name: nodejs setup
  tags:
  - deployment
  #ansible.builtin.import_role:
  ansible.builtin.include_role:
    name: common
    taks_from: nodejs-setup.yaml

- name: systemd setup
  ansible.builtin.import_role:
    name: common
    taks_from: systemd-setup.yaml

- name: copy mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: check products loaded
  ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output

- name: print the output
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"

- name: load the products
  ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
  when: catalogue_output.stdout  | int < 0

- name: start catalogue
  ansible.builtin.service:
    name: catalogue
    state: restarted
    enabled: yes

# execution process
# 1. ansible finds the meta directory execute main.yaml 
# 2. it depends on the common role
# 3. ansible executes in common/tasks/main.yaml
# 4. now ansible executes the catalogue/tasks/main.yaml
# 5. we extracted  common code into  common/app-setup.yaml
# 6. ansible imports  this into catalogue/tasks/main.yaml
