ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-dev.sanathananelaform.online
CATALOGUE_HOST: catalogue-dev.sanathananelaform.online
REDIS_HOST: redis-dev.sanathananelaform.online
USER_HOST: user-dev.sanathananelaform.online
CART_HOST: cart-dev.sanathananelaform.online
MYSQL_HOST: mysql-dev.sanathananelaform.online
SHIPPING_HOST: shipping-dev.sanathananelaform.online
RABBITMQ_HOST: rabbitmq-dev.sanathananelaform.online
PAYMENT_HOST: payment-dev.sanathananelaform.onlin
